spring:
  application:
    name: airport

  config:
    import:
      - optional:file:.env[.properties]

  cloud:
    gateway:
      httpclient:
        pool:
          max-idle-time: 2000
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origins:
              - https://www.byuljogak.com
              - https://byuljogak.com
              - https://tarot.byuljogak.com
              - https://admin.byuljogak.com
              - https://*.byuljogak.com
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
            allow-credentials: true
            allowed-headers: "*"
      routes:
        - id: member_auth
          uri: ${AUTH_URI}
          predicates:
            - Path=/auth/signin/{segment}, /auth/enroll/{segment}
          filters:
            - StripPrefix=1
            - SessionIssueFilter
        - id: member_manage
          uri: ${AUTH_URI}
          predicates:
            - Path=/auth/delete/{segment}, /auth/modify/{segment}
          filters:
            - StripPrefix=1
            - name: SessionValidateFilter
              args:
                sessionAttributes: uuid, test

  session:
    redis:
      namespace: session

  data:
    redis:
      host: ${SESSION_HOST}
      port: ${SESSION_PORT}

server:
  ssl:
    enabled: ${SSL_ENABLED}
    key-alias: ${SSL_KEY_ALIAS}
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-store: keystore.p12
    key-store-type: PKCS12
