spring:
  application:
    name: airport

  config:
    import:
      - optional:file:.env[.properties]

  cloud:
    gateway:
      routes:
        # Change below to your services
        - id: your_service
          uri: ${YOUR_SERVICE_URI}
          predicates:
            - Path=/your_service/**
          filters:
            - StripPrefix=1
            - SessionIssueFilter
            - SessionValidateFilter

  session:
    redis:
      namespace: session

  data:
    redis:
      host: ${SESSION_HOST}
      port: ${SESSION_PORT}

server:
  ssl:
    enabled: ${SSL_ENABLED}
    key-alias: ${SSL_KEY_ALIAS}
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-store: keystore.p12
    key-store-type: PKCS12
